name: Enhance workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        required: true
        default: "Pavithra"

env:
  COURSE: DevOps

jobs:
  greet:
    runs-on: ubuntu-latest 

    steps:
      - name: Greeting
        run: echo "Hello,${{inputs.name}}!"

      - name: Runner Details
        run: |
          echo "operating System: ${{ runner.os}}"
          echo "Architecture: ${{ runner.arch}}"
          
      - name: User input
        run: echo"your name is: ${{inputs.name}}"

      - name: Environment Variable
        eun: echo " Course: $COURSE"

      - name: Secret
        run: echo "Secret: ${{ Secrets.MY_SECRET }}"

      - name: Admin bonus
        if: ${{inputs.name == 'admin' }}
        run: echo "Welcome Admin!"

    
